// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/network/standard"
	"github.com/hertz-contrib/cors"
	"github.com/hertz-contrib/gzip"
)

func main() {
	h := server.Default(
		server.WithStreamBody(true),
		server.WithTransport(standard.NewTransporter),
		server.WithHostPorts("0.0.0.0:8080"),
		server.WithHandleMethodNotAllowed(true))
	h.Use(cors.New(cors.Config{AllowAllOrigins: true}))
	h.Use(gzip.Gzip(gzip.DefaultCompression))
	register(h)
	h.Spin()
}
