// Code generated by hertz generator.

package main

import (
	zaplog "dousheng_server/deploy/log"
	"dousheng_server/middleware/limiter"
	"github.com/cloudwego/hertz/pkg/app/server"
	"github.com/cloudwego/hertz/pkg/network/standard"
	"github.com/hertz-contrib/cors"
	"github.com/hertz-contrib/gzip"
	"github.com/hertz-contrib/monitor-prometheus"
)

func main() {
	limiter.InitLimiter()
	zaplog.InitLogger()
	h := server.Default(
		server.WithStreamBody(true),
		server.WithTransport(standard.NewTransporter),
		server.WithHostPorts("0.0.0.0:8080"),
		server.WithHandleMethodNotAllowed(true),
		server.WithTracer(prometheus.NewServerTracer(":9080", "/metrics")))

	// 使用限流中间件
	h.Use(limiter.LimiterMiddleware())
	h.Use(cors.New(cors.Config{AllowAllOrigins: true}))
	h.Use(gzip.Gzip(gzip.DefaultCompression))
	register(h)
	h.Spin()
}
