// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.6.1
// source: idl/snowflake.proto

package kitex_gen

import (
	context "context"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewIDRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NewIDRequest) Reset() {
	*x = NewIDRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_snowflake_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewIDRequest) ProtoMessage() {}

func (x *NewIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_idl_snowflake_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewIDRequest.ProtoReflect.Descriptor instead.
func (*NewIDRequest) Descriptor() ([]byte, []int) {
	return file_idl_snowflake_proto_rawDescGZIP(), []int{0}
}

type NewIDResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ID int64 `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
}

func (x *NewIDResponse) Reset() {
	*x = NewIDResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_idl_snowflake_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewIDResponse) ProtoMessage() {}

func (x *NewIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_idl_snowflake_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewIDResponse.ProtoReflect.Descriptor instead.
func (*NewIDResponse) Descriptor() ([]byte, []int) {
	return file_idl_snowflake_proto_rawDescGZIP(), []int{1}
}

func (x *NewIDResponse) GetID() int64 {
	if x != nil {
		return x.ID
	}
	return 0
}

var File_idl_snowflake_proto protoreflect.FileDescriptor

var file_idl_snowflake_proto_rawDesc = []byte{
	0x0a, 0x13, 0x69, 0x64, 0x6c, 0x2f, 0x73, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09, 0x73, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65,
	0x22, 0x0e, 0x0a, 0x0c, 0x4e, 0x65, 0x77, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x22, 0x1f, 0x0a, 0x0d, 0x4e, 0x65, 0x77, 0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49,
	0x44, 0x32, 0x47, 0x0a, 0x09, 0x53, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x12, 0x3a,
	0x0a, 0x05, 0x4e, 0x65, 0x77, 0x49, 0x44, 0x12, 0x17, 0x2e, 0x73, 0x6e, 0x6f, 0x77, 0x66, 0x6c,
	0x61, 0x6b, 0x65, 0x2e, 0x4e, 0x65, 0x77, 0x49, 0x44, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x18, 0x2e, 0x73, 0x6e, 0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x2e, 0x4e, 0x65, 0x77,
	0x49, 0x44, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x37, 0x5a, 0x35, 0x64, 0x6f,
	0x75, 0x73, 0x68, 0x65, 0x6e, 0x67, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x73, 0x6e,
	0x6f, 0x77, 0x66, 0x6c, 0x61, 0x6b, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2f,
	0x6b, 0x69, 0x74, 0x65, 0x78, 0x5f, 0x67, 0x65, 0x6e, 0x2f, 0x6b, 0x69, 0x74, 0x65, 0x78, 0x5f,
	0x67, 0x65, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_idl_snowflake_proto_rawDescOnce sync.Once
	file_idl_snowflake_proto_rawDescData = file_idl_snowflake_proto_rawDesc
)

func file_idl_snowflake_proto_rawDescGZIP() []byte {
	file_idl_snowflake_proto_rawDescOnce.Do(func() {
		file_idl_snowflake_proto_rawDescData = protoimpl.X.CompressGZIP(file_idl_snowflake_proto_rawDescData)
	})
	return file_idl_snowflake_proto_rawDescData
}

var file_idl_snowflake_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_idl_snowflake_proto_goTypes = []interface{}{
	(*NewIDRequest)(nil),  // 0: snowflake.NewIDRequest
	(*NewIDResponse)(nil), // 1: snowflake.NewIDResponse
}
var file_idl_snowflake_proto_depIdxs = []int32{
	0, // 0: snowflake.Snowflake.NewID:input_type -> snowflake.NewIDRequest
	1, // 1: snowflake.Snowflake.NewID:output_type -> snowflake.NewIDResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_idl_snowflake_proto_init() }
func file_idl_snowflake_proto_init() {
	if File_idl_snowflake_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_idl_snowflake_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewIDRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_idl_snowflake_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NewIDResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_idl_snowflake_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_snowflake_proto_goTypes,
		DependencyIndexes: file_idl_snowflake_proto_depIdxs,
		MessageInfos:      file_idl_snowflake_proto_msgTypes,
	}.Build()
	File_idl_snowflake_proto = out.File
	file_idl_snowflake_proto_rawDesc = nil
	file_idl_snowflake_proto_goTypes = nil
	file_idl_snowflake_proto_depIdxs = nil
}

var _ context.Context

// Code generated by Kitex v0.4.4. DO NOT EDIT.

type Snowflake interface {
	NewID(ctx context.Context, req *NewIDRequest) (res *NewIDResponse, err error)
}
