// Code generated by hertz generator.

package handler

import (
	"context"
	"dousheng_server/user_service/kitex_gen/kitex_gen/usercenter"
	"github.com/cloudwego/kitex/client"
	"github.com/kitex-contrib/obs-opentelemetry/tracing"
	etcd "github.com/kitex-contrib/registry-etcd"

	"github.com/cloudwego/hertz/pkg/app"
)

// Ping .
func Ping(ctx context.Context, c *app.RequestContext) {
	r, err := etcd.NewEtcdResolver([]string{"192.168.1.18:2379"})
	if err != nil {
		panic(err)
	}

	c, err := usercenter.NewClient(
		"userservice",
		client.WithResolver(r),
		client.WithSuite(tracing.NewClientSuite()),
	)
}
