scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s  #global catch time
    static_configs:
      - targets: ['0.0.0.0:9090']

  - job_name: 'rpc-user'
    static_configs:
      - targets: [ '127.0.0.1:8900' ]
        labels:
          job: rpc-user
          app: rpc-user
          env: dev

  - job_name: 'rpc-snowflake'
    static_configs:
      - targets: ['127.0.0.1:8901']
        labels:
          job: rpc-snowflake
          app: rpc-snowflake
          env: dev

  - job_name: 'rpc-video'
    static_configs:
      - targets: ['127.0.0.1:8902']
        labels:
          job: rpc-video
          app: rpc-video
          env: dev
