// Code generated by Kitex v0.4.4. DO NOT EDIT.

package videocenter

import (
	"context"
	kitex_gen "dousheng_server/video_service/kitex_gen"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	Publish(ctx context.Context, Req *kitex_gen.PublishRequest, callOptions ...callopt.Option) (r *kitex_gen.PublishResponse, err error)
	Delete(ctx context.Context, Req *kitex_gen.DeleteRequest, callOptions ...callopt.Option) (r *kitex_gen.BasicResponse, err error)
	Feed(ctx context.Context, Req *kitex_gen.FeedRequest, callOptions ...callopt.Option) (r *kitex_gen.FeedResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kVideoCenterClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kVideoCenterClient struct {
	*kClient
}

func (p *kVideoCenterClient) Publish(ctx context.Context, Req *kitex_gen.PublishRequest, callOptions ...callopt.Option) (r *kitex_gen.PublishResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Publish(ctx, Req)
}

func (p *kVideoCenterClient) Delete(ctx context.Context, Req *kitex_gen.DeleteRequest, callOptions ...callopt.Option) (r *kitex_gen.BasicResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Delete(ctx, Req)
}

func (p *kVideoCenterClient) Feed(ctx context.Context, Req *kitex_gen.FeedRequest, callOptions ...callopt.Option) (r *kitex_gen.FeedResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.Feed(ctx, Req)
}
