// Code generated by Kitex v0.4.4. DO NOT EDIT.

package videocenter

import (
	"context"
	kitex_gen "dousheng_server/video_service/kitex_gen"
	"fmt"
	client "github.com/cloudwego/kitex/client"
	kitex "github.com/cloudwego/kitex/pkg/serviceinfo"
	streaming "github.com/cloudwego/kitex/pkg/streaming"
	proto "google.golang.org/protobuf/proto"
)

func serviceInfo() *kitex.ServiceInfo {
	return videoCenterServiceInfo
}

var videoCenterServiceInfo = NewServiceInfo()

func NewServiceInfo() *kitex.ServiceInfo {
	serviceName := "VideoCenter"
	handlerType := (*kitex_gen.VideoCenter)(nil)
	methods := map[string]kitex.MethodInfo{
		"Publish":          kitex.NewMethodInfo(publishHandler, newPublishArgs, newPublishResult, false),
		"Delete":           kitex.NewMethodInfo(deleteHandler, newDeleteArgs, newDeleteResult, false),
		"Feed":             kitex.NewMethodInfo(feedHandler, newFeedArgs, newFeedResult, false),
		"VideoList":        kitex.NewMethodInfo(videoListHandler, newVideoListArgs, newVideoListResult, false),
		"Like":             kitex.NewMethodInfo(likeHandler, newLikeArgs, newLikeResult, false),
		"GetVideo":         kitex.NewMethodInfo(getVideoHandler, newGetVideoArgs, newGetVideoResult, false),
		"GetFavoriteVideo": kitex.NewMethodInfo(getFavoriteVideoHandler, newGetFavoriteVideoArgs, newGetFavoriteVideoResult, false),
	}
	extra := map[string]interface{}{
		"PackageName": "video",
	}
	svcInfo := &kitex.ServiceInfo{
		ServiceName:     serviceName,
		HandlerType:     handlerType,
		Methods:         methods,
		PayloadCodec:    kitex.Protobuf,
		KiteXGenVersion: "v0.4.4",
		Extra:           extra,
	}
	return svcInfo
}

func publishHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(kitex_gen.PublishRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(kitex_gen.VideoCenter).Publish(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *PublishArgs:
		success, err := handler.(kitex_gen.VideoCenter).Publish(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*PublishResult)
		realResult.Success = success
	}
	return nil
}
func newPublishArgs() interface{} {
	return &PublishArgs{}
}

func newPublishResult() interface{} {
	return &PublishResult{}
}

type PublishArgs struct {
	Req *kitex_gen.PublishRequest
}

func (p *PublishArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(kitex_gen.PublishRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *PublishArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *PublishArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *PublishArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in PublishArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *PublishArgs) Unmarshal(in []byte) error {
	msg := new(kitex_gen.PublishRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var PublishArgs_Req_DEFAULT *kitex_gen.PublishRequest

func (p *PublishArgs) GetReq() *kitex_gen.PublishRequest {
	if !p.IsSetReq() {
		return PublishArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *PublishArgs) IsSetReq() bool {
	return p.Req != nil
}

type PublishResult struct {
	Success *kitex_gen.PublishResponse
}

var PublishResult_Success_DEFAULT *kitex_gen.PublishResponse

func (p *PublishResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(kitex_gen.PublishResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *PublishResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *PublishResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *PublishResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in PublishResult")
	}
	return proto.Marshal(p.Success)
}

func (p *PublishResult) Unmarshal(in []byte) error {
	msg := new(kitex_gen.PublishResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *PublishResult) GetSuccess() *kitex_gen.PublishResponse {
	if !p.IsSetSuccess() {
		return PublishResult_Success_DEFAULT
	}
	return p.Success
}

func (p *PublishResult) SetSuccess(x interface{}) {
	p.Success = x.(*kitex_gen.PublishResponse)
}

func (p *PublishResult) IsSetSuccess() bool {
	return p.Success != nil
}

func deleteHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(kitex_gen.DeleteRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(kitex_gen.VideoCenter).Delete(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *DeleteArgs:
		success, err := handler.(kitex_gen.VideoCenter).Delete(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*DeleteResult)
		realResult.Success = success
	}
	return nil
}
func newDeleteArgs() interface{} {
	return &DeleteArgs{}
}

func newDeleteResult() interface{} {
	return &DeleteResult{}
}

type DeleteArgs struct {
	Req *kitex_gen.DeleteRequest
}

func (p *DeleteArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(kitex_gen.DeleteRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *DeleteArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *DeleteArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *DeleteArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in DeleteArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *DeleteArgs) Unmarshal(in []byte) error {
	msg := new(kitex_gen.DeleteRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var DeleteArgs_Req_DEFAULT *kitex_gen.DeleteRequest

func (p *DeleteArgs) GetReq() *kitex_gen.DeleteRequest {
	if !p.IsSetReq() {
		return DeleteArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *DeleteArgs) IsSetReq() bool {
	return p.Req != nil
}

type DeleteResult struct {
	Success *kitex_gen.BasicResponse
}

var DeleteResult_Success_DEFAULT *kitex_gen.BasicResponse

func (p *DeleteResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(kitex_gen.BasicResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *DeleteResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *DeleteResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *DeleteResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in DeleteResult")
	}
	return proto.Marshal(p.Success)
}

func (p *DeleteResult) Unmarshal(in []byte) error {
	msg := new(kitex_gen.BasicResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *DeleteResult) GetSuccess() *kitex_gen.BasicResponse {
	if !p.IsSetSuccess() {
		return DeleteResult_Success_DEFAULT
	}
	return p.Success
}

func (p *DeleteResult) SetSuccess(x interface{}) {
	p.Success = x.(*kitex_gen.BasicResponse)
}

func (p *DeleteResult) IsSetSuccess() bool {
	return p.Success != nil
}

func feedHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(kitex_gen.FeedRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(kitex_gen.VideoCenter).Feed(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *FeedArgs:
		success, err := handler.(kitex_gen.VideoCenter).Feed(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*FeedResult)
		realResult.Success = success
	}
	return nil
}
func newFeedArgs() interface{} {
	return &FeedArgs{}
}

func newFeedResult() interface{} {
	return &FeedResult{}
}

type FeedArgs struct {
	Req *kitex_gen.FeedRequest
}

func (p *FeedArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(kitex_gen.FeedRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *FeedArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *FeedArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *FeedArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in FeedArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *FeedArgs) Unmarshal(in []byte) error {
	msg := new(kitex_gen.FeedRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var FeedArgs_Req_DEFAULT *kitex_gen.FeedRequest

func (p *FeedArgs) GetReq() *kitex_gen.FeedRequest {
	if !p.IsSetReq() {
		return FeedArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *FeedArgs) IsSetReq() bool {
	return p.Req != nil
}

type FeedResult struct {
	Success *kitex_gen.FeedResponse
}

var FeedResult_Success_DEFAULT *kitex_gen.FeedResponse

func (p *FeedResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(kitex_gen.FeedResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *FeedResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *FeedResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *FeedResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in FeedResult")
	}
	return proto.Marshal(p.Success)
}

func (p *FeedResult) Unmarshal(in []byte) error {
	msg := new(kitex_gen.FeedResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *FeedResult) GetSuccess() *kitex_gen.FeedResponse {
	if !p.IsSetSuccess() {
		return FeedResult_Success_DEFAULT
	}
	return p.Success
}

func (p *FeedResult) SetSuccess(x interface{}) {
	p.Success = x.(*kitex_gen.FeedResponse)
}

func (p *FeedResult) IsSetSuccess() bool {
	return p.Success != nil
}

func videoListHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(kitex_gen.VideoListRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(kitex_gen.VideoCenter).VideoList(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *VideoListArgs:
		success, err := handler.(kitex_gen.VideoCenter).VideoList(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*VideoListResult)
		realResult.Success = success
	}
	return nil
}
func newVideoListArgs() interface{} {
	return &VideoListArgs{}
}

func newVideoListResult() interface{} {
	return &VideoListResult{}
}

type VideoListArgs struct {
	Req *kitex_gen.VideoListRequest
}

func (p *VideoListArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(kitex_gen.VideoListRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *VideoListArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *VideoListArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *VideoListArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in VideoListArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *VideoListArgs) Unmarshal(in []byte) error {
	msg := new(kitex_gen.VideoListRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var VideoListArgs_Req_DEFAULT *kitex_gen.VideoListRequest

func (p *VideoListArgs) GetReq() *kitex_gen.VideoListRequest {
	if !p.IsSetReq() {
		return VideoListArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *VideoListArgs) IsSetReq() bool {
	return p.Req != nil
}

type VideoListResult struct {
	Success *kitex_gen.VideoListResponse
}

var VideoListResult_Success_DEFAULT *kitex_gen.VideoListResponse

func (p *VideoListResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(kitex_gen.VideoListResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *VideoListResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *VideoListResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *VideoListResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in VideoListResult")
	}
	return proto.Marshal(p.Success)
}

func (p *VideoListResult) Unmarshal(in []byte) error {
	msg := new(kitex_gen.VideoListResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *VideoListResult) GetSuccess() *kitex_gen.VideoListResponse {
	if !p.IsSetSuccess() {
		return VideoListResult_Success_DEFAULT
	}
	return p.Success
}

func (p *VideoListResult) SetSuccess(x interface{}) {
	p.Success = x.(*kitex_gen.VideoListResponse)
}

func (p *VideoListResult) IsSetSuccess() bool {
	return p.Success != nil
}

func likeHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(kitex_gen.LikeRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(kitex_gen.VideoCenter).Like(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *LikeArgs:
		success, err := handler.(kitex_gen.VideoCenter).Like(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*LikeResult)
		realResult.Success = success
	}
	return nil
}
func newLikeArgs() interface{} {
	return &LikeArgs{}
}

func newLikeResult() interface{} {
	return &LikeResult{}
}

type LikeArgs struct {
	Req *kitex_gen.LikeRequest
}

func (p *LikeArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(kitex_gen.LikeRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *LikeArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *LikeArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *LikeArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in LikeArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *LikeArgs) Unmarshal(in []byte) error {
	msg := new(kitex_gen.LikeRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var LikeArgs_Req_DEFAULT *kitex_gen.LikeRequest

func (p *LikeArgs) GetReq() *kitex_gen.LikeRequest {
	if !p.IsSetReq() {
		return LikeArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *LikeArgs) IsSetReq() bool {
	return p.Req != nil
}

type LikeResult struct {
	Success *kitex_gen.BasicResponse
}

var LikeResult_Success_DEFAULT *kitex_gen.BasicResponse

func (p *LikeResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(kitex_gen.BasicResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *LikeResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *LikeResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *LikeResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in LikeResult")
	}
	return proto.Marshal(p.Success)
}

func (p *LikeResult) Unmarshal(in []byte) error {
	msg := new(kitex_gen.BasicResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *LikeResult) GetSuccess() *kitex_gen.BasicResponse {
	if !p.IsSetSuccess() {
		return LikeResult_Success_DEFAULT
	}
	return p.Success
}

func (p *LikeResult) SetSuccess(x interface{}) {
	p.Success = x.(*kitex_gen.BasicResponse)
}

func (p *LikeResult) IsSetSuccess() bool {
	return p.Success != nil
}

func getVideoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(kitex_gen.GetVideoRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(kitex_gen.VideoCenter).GetVideo(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *GetVideoArgs:
		success, err := handler.(kitex_gen.VideoCenter).GetVideo(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetVideoResult)
		realResult.Success = success
	}
	return nil
}
func newGetVideoArgs() interface{} {
	return &GetVideoArgs{}
}

func newGetVideoResult() interface{} {
	return &GetVideoResult{}
}

type GetVideoArgs struct {
	Req *kitex_gen.GetVideoRequest
}

func (p *GetVideoArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(kitex_gen.GetVideoRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetVideoArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetVideoArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetVideoArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in GetVideoArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *GetVideoArgs) Unmarshal(in []byte) error {
	msg := new(kitex_gen.GetVideoRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetVideoArgs_Req_DEFAULT *kitex_gen.GetVideoRequest

func (p *GetVideoArgs) GetReq() *kitex_gen.GetVideoRequest {
	if !p.IsSetReq() {
		return GetVideoArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetVideoArgs) IsSetReq() bool {
	return p.Req != nil
}

type GetVideoResult struct {
	Success *kitex_gen.GetVideoResponse
}

var GetVideoResult_Success_DEFAULT *kitex_gen.GetVideoResponse

func (p *GetVideoResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(kitex_gen.GetVideoResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetVideoResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetVideoResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetVideoResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in GetVideoResult")
	}
	return proto.Marshal(p.Success)
}

func (p *GetVideoResult) Unmarshal(in []byte) error {
	msg := new(kitex_gen.GetVideoResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetVideoResult) GetSuccess() *kitex_gen.GetVideoResponse {
	if !p.IsSetSuccess() {
		return GetVideoResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetVideoResult) SetSuccess(x interface{}) {
	p.Success = x.(*kitex_gen.GetVideoResponse)
}

func (p *GetVideoResult) IsSetSuccess() bool {
	return p.Success != nil
}

func getFavoriteVideoHandler(ctx context.Context, handler interface{}, arg, result interface{}) error {
	switch s := arg.(type) {
	case *streaming.Args:
		st := s.Stream
		req := new(kitex_gen.GetVideoRequest)
		if err := st.RecvMsg(req); err != nil {
			return err
		}
		resp, err := handler.(kitex_gen.VideoCenter).GetFavoriteVideo(ctx, req)
		if err != nil {
			return err
		}
		if err := st.SendMsg(resp); err != nil {
			return err
		}
	case *GetFavoriteVideoArgs:
		success, err := handler.(kitex_gen.VideoCenter).GetFavoriteVideo(ctx, s.Req)
		if err != nil {
			return err
		}
		realResult := result.(*GetFavoriteVideoResult)
		realResult.Success = success
	}
	return nil
}
func newGetFavoriteVideoArgs() interface{} {
	return &GetFavoriteVideoArgs{}
}

func newGetFavoriteVideoResult() interface{} {
	return &GetFavoriteVideoResult{}
}

type GetFavoriteVideoArgs struct {
	Req *kitex_gen.GetVideoRequest
}

func (p *GetFavoriteVideoArgs) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetReq() {
		p.Req = new(kitex_gen.GetVideoRequest)
	}
	return p.Req.FastRead(buf, _type, number)
}

func (p *GetFavoriteVideoArgs) FastWrite(buf []byte) (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.FastWrite(buf)
}

func (p *GetFavoriteVideoArgs) Size() (n int) {
	if !p.IsSetReq() {
		return 0
	}
	return p.Req.Size()
}

func (p *GetFavoriteVideoArgs) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetReq() {
		return out, fmt.Errorf("No req in GetFavoriteVideoArgs")
	}
	return proto.Marshal(p.Req)
}

func (p *GetFavoriteVideoArgs) Unmarshal(in []byte) error {
	msg := new(kitex_gen.GetVideoRequest)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Req = msg
	return nil
}

var GetFavoriteVideoArgs_Req_DEFAULT *kitex_gen.GetVideoRequest

func (p *GetFavoriteVideoArgs) GetReq() *kitex_gen.GetVideoRequest {
	if !p.IsSetReq() {
		return GetFavoriteVideoArgs_Req_DEFAULT
	}
	return p.Req
}

func (p *GetFavoriteVideoArgs) IsSetReq() bool {
	return p.Req != nil
}

type GetFavoriteVideoResult struct {
	Success *kitex_gen.GetFavoriteVideosResponse
}

var GetFavoriteVideoResult_Success_DEFAULT *kitex_gen.GetFavoriteVideosResponse

func (p *GetFavoriteVideoResult) FastRead(buf []byte, _type int8, number int32) (n int, err error) {
	if !p.IsSetSuccess() {
		p.Success = new(kitex_gen.GetFavoriteVideosResponse)
	}
	return p.Success.FastRead(buf, _type, number)
}

func (p *GetFavoriteVideoResult) FastWrite(buf []byte) (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.FastWrite(buf)
}

func (p *GetFavoriteVideoResult) Size() (n int) {
	if !p.IsSetSuccess() {
		return 0
	}
	return p.Success.Size()
}

func (p *GetFavoriteVideoResult) Marshal(out []byte) ([]byte, error) {
	if !p.IsSetSuccess() {
		return out, fmt.Errorf("No req in GetFavoriteVideoResult")
	}
	return proto.Marshal(p.Success)
}

func (p *GetFavoriteVideoResult) Unmarshal(in []byte) error {
	msg := new(kitex_gen.GetFavoriteVideosResponse)
	if err := proto.Unmarshal(in, msg); err != nil {
		return err
	}
	p.Success = msg
	return nil
}

func (p *GetFavoriteVideoResult) GetSuccess() *kitex_gen.GetFavoriteVideosResponse {
	if !p.IsSetSuccess() {
		return GetFavoriteVideoResult_Success_DEFAULT
	}
	return p.Success
}

func (p *GetFavoriteVideoResult) SetSuccess(x interface{}) {
	p.Success = x.(*kitex_gen.GetFavoriteVideosResponse)
}

func (p *GetFavoriteVideoResult) IsSetSuccess() bool {
	return p.Success != nil
}

type kClient struct {
	c client.Client
}

func newServiceClient(c client.Client) *kClient {
	return &kClient{
		c: c,
	}
}

func (p *kClient) Publish(ctx context.Context, Req *kitex_gen.PublishRequest) (r *kitex_gen.PublishResponse, err error) {
	var _args PublishArgs
	_args.Req = Req
	var _result PublishResult
	if err = p.c.Call(ctx, "Publish", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Delete(ctx context.Context, Req *kitex_gen.DeleteRequest) (r *kitex_gen.BasicResponse, err error) {
	var _args DeleteArgs
	_args.Req = Req
	var _result DeleteResult
	if err = p.c.Call(ctx, "Delete", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Feed(ctx context.Context, Req *kitex_gen.FeedRequest) (r *kitex_gen.FeedResponse, err error) {
	var _args FeedArgs
	_args.Req = Req
	var _result FeedResult
	if err = p.c.Call(ctx, "Feed", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) VideoList(ctx context.Context, Req *kitex_gen.VideoListRequest) (r *kitex_gen.VideoListResponse, err error) {
	var _args VideoListArgs
	_args.Req = Req
	var _result VideoListResult
	if err = p.c.Call(ctx, "VideoList", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) Like(ctx context.Context, Req *kitex_gen.LikeRequest) (r *kitex_gen.BasicResponse, err error) {
	var _args LikeArgs
	_args.Req = Req
	var _result LikeResult
	if err = p.c.Call(ctx, "Like", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetVideo(ctx context.Context, Req *kitex_gen.GetVideoRequest) (r *kitex_gen.GetVideoResponse, err error) {
	var _args GetVideoArgs
	_args.Req = Req
	var _result GetVideoResult
	if err = p.c.Call(ctx, "GetVideo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}

func (p *kClient) GetFavoriteVideo(ctx context.Context, Req *kitex_gen.GetVideoRequest) (r *kitex_gen.GetFavoriteVideosResponse, err error) {
	var _args GetFavoriteVideoArgs
	_args.Req = Req
	var _result GetFavoriteVideoResult
	if err = p.c.Call(ctx, "GetFavoriteVideo", &_args, &_result); err != nil {
		return
	}
	return _result.GetSuccess(), nil
}
