scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 15s  #global catch time
    static_configs:
      - targets: ['0.0.0.0:9090']

  - job_name: 'rpc-user'
    static_configs:
      - targets: [ 'localhost:9900' ]
        labels:
          job: rpc-user
          app: rpc-user
          env: dev

  - job_name: 'rpc-snowflake'
    static_configs:
      - targets: ['localhost:9901']
        labels:
          job: rpc-snowflake
          app: rpc-snowflake
          env: dev

  - job_name: 'rpc-video'
    static_configs:
      - targets: ['localhost:9902']
        labels:
          job: rpc-video
          app: rpc-video
          env: dev

  - job_name: 'api-hertz'
    static_configs:
      - targets: ['localhost:9080']
        labels:
          job: api-hertz
          app: api-hertz
          env: dev

  - job_name: 'mysql'
    static_configs:
      - targets: ['localhost:9104']
        labels:
          job: mysql
          app: mysql

  - job_name: 'linux'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          job: linux
